


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_hashids" WITH SCHEMA "public";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE OR REPLACE FUNCTION "public"."generate_short_id"() RETURNS "text"
    LANGUAGE "plpgsql"
    AS $$
DECLARE
  chars TEXT := '0123456789ABCDEFGHJKMNPQRSTUVWXYZabcdefghjkmnpqrstuvwxyz'; -- 57 chars, no confusing 0/O/I/l
  result TEXT := '';
  i INT;
BEGIN
  -- Generate 7 random chars
  FOR i IN 1..7 LOOP
    result := result || substr(chars, (floor(random() * length(chars))::int + 1), 1);
  END LOOP;
  RETURN result;
END;
$$;


ALTER FUNCTION "public"."generate_short_id"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."generate_short_id"("input_uuid" "uuid", "length" integer DEFAULT 5) RETURNS "text"
    LANGUAGE "plpgsql"
    AS $$
BEGIN
  RETURN id_encode(hashtext(input_uuid::text)::bigint, length);
END;
$$;


ALTER FUNCTION "public"."generate_short_id"("input_uuid" "uuid", "length" integer) OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."bookings" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "startDate" timestamp without time zone,
    "endDate" timestamp without time zone,
    "numNights" smallint,
    "numGuests" smallint,
    "cabinPrice" real,
    "extrasPrice" real,
    "totalPrice" real,
    "status" "text",
    "hasBreakfast" boolean,
    "isPaid" boolean,
    "observations" "text",
    "cabinId" bigint,
    "guestId" bigint
);


ALTER TABLE "public"."bookings" OWNER TO "postgres";


ALTER TABLE "public"."bookings" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."bookings_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."cabins" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text",
    "maxCapacity" smallint,
    "regularPrice" smallint,
    "discount" smallint,
    "description" "text",
    "image" "text"
);


ALTER TABLE "public"."cabins" OWNER TO "postgres";


ALTER TABLE "public"."cabins" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."cabins_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."guests" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "fullName" "text",
    "email" "text",
    "nationalID" "text",
    "nationality" "text",
    "countryFlag" "text"
);


ALTER TABLE "public"."guests" OWNER TO "postgres";


ALTER TABLE "public"."guests" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."guests_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."menu" (
    "id" bigint NOT NULL,
    "name" "text",
    "unitPrice" bigint,
    "imageUrl" "text",
    "soldOut" boolean,
    "ingredients" "jsonb"
);


ALTER TABLE "public"."menu" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."orders" (
    "id" bigint NOT NULL,
    "createdAt" timestamp with time zone DEFAULT "now"() NOT NULL,
    "customer" "text",
    "phone" "text",
    "position" "text",
    "address" "text",
    "status" "text" DEFAULT '"preparing"'::"text",
    "cart" "jsonb"
);


ALTER TABLE "public"."orders" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."ordersPizza" (
    "shortId" bigint NOT NULL,
    "createdAt" timestamp with time zone DEFAULT "now"() NOT NULL,
    "customer" "text",
    "phone" "text",
    "position" "text" DEFAULT ''::"text",
    "address" "text",
    "status" "text" DEFAULT 'preparing'::"text",
    "cart" "jsonb",
    "estimatedDelivery" timestamp with time zone DEFAULT ("now"() + '01:00:00'::interval),
    "priority" boolean,
    "id" "text" DEFAULT "public"."generate_short_id"()
);


ALTER TABLE "public"."ordersPizza" OWNER TO "postgres";


ALTER TABLE "public"."ordersPizza" ALTER COLUMN "shortId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."orders-pizza_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE "public"."orders" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."orders_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."settings" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "minBookingLength" smallint,
    "maxBookingLength" smallint,
    "maxGuestsPerBooking" smallint,
    "breakfastPrice" real
);


ALTER TABLE "public"."settings" OWNER TO "postgres";


ALTER TABLE "public"."settings" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."settings_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."worldwise" (
    "id" bigint NOT NULL,
    "date" timestamp with time zone DEFAULT "now"() NOT NULL,
    "position" json,
    "cityName" "text",
    "country" "text",
    "emoji" "text",
    "notes" "text"
);


ALTER TABLE "public"."worldwise" OWNER TO "postgres";


ALTER TABLE "public"."worldwise" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."worldwise_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."bookings"
    ADD CONSTRAINT "bookings_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."cabins"
    ADD CONSTRAINT "cabins_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."guests"
    ADD CONSTRAINT "guests_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."menu"
    ADD CONSTRAINT "menu_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."ordersPizza"
    ADD CONSTRAINT "orders-pizza_pkey" PRIMARY KEY ("shortId");



ALTER TABLE ONLY "public"."ordersPizza"
    ADD CONSTRAINT "ordersPizza_id_key" UNIQUE ("id");



ALTER TABLE ONLY "public"."settings"
    ADD CONSTRAINT "settings_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."worldwise"
    ADD CONSTRAINT "worldwise_pkey" PRIMARY KEY ("id");



CREATE UNIQUE INDEX "orderspizza_short_id_unique" ON "public"."ordersPizza" USING "btree" ("id");



ALTER TABLE ONLY "public"."bookings"
    ADD CONSTRAINT "bookings_cabinId_fkey" FOREIGN KEY ("cabinId") REFERENCES "public"."cabins"("id");



ALTER TABLE ONLY "public"."bookings"
    ADD CONSTRAINT "bookings_guestId_fkey" FOREIGN KEY ("guestId") REFERENCES "public"."guests"("id");



CREATE POLICY "Delete all" ON "public"."ordersPizza" FOR DELETE USING (true);



CREATE POLICY "Delete all" ON "public"."worldwise" FOR DELETE USING (true);



CREATE POLICY "Delete all " ON "public"."settings" FOR DELETE USING (true);



CREATE POLICY "Enable create cabin" ON "public"."cabins" FOR INSERT WITH CHECK (true);



CREATE POLICY "Enable delete for all users" ON "public"."cabins" FOR DELETE USING (true);



CREATE POLICY "Enable read access for all users" ON "public"."bookings" FOR SELECT USING (true);



CREATE POLICY "Enable read access for all users" ON "public"."cabins" FOR SELECT USING (true);



CREATE POLICY "Enable read access for all users" ON "public"."guests" FOR SELECT USING (true);



CREATE POLICY "Enable read access for all users" ON "public"."settings" FOR SELECT USING (true);



CREATE POLICY "Enable update cabin" ON "public"."cabins" FOR UPDATE USING (true) WITH CHECK (true);



CREATE POLICY "Inser all" ON "public"."settings" FOR INSERT WITH CHECK (true);



CREATE POLICY "Insert all" ON "public"."ordersPizza" FOR INSERT WITH CHECK (true);



CREATE POLICY "Insert all" ON "public"."worldwise" FOR INSERT WITH CHECK (true);



CREATE POLICY "Select all" ON "public"."menu" FOR SELECT USING (true);



CREATE POLICY "Select all" ON "public"."ordersPizza" FOR SELECT USING (true);



CREATE POLICY "Select all" ON "public"."worldwise" FOR SELECT USING (true);



CREATE POLICY "Update all" ON "public"."ordersPizza" FOR UPDATE USING (true) WITH CHECK (true);



CREATE POLICY "Update all" ON "public"."settings" FOR UPDATE USING (true) WITH CHECK (true);



CREATE POLICY "Update all" ON "public"."worldwise" FOR UPDATE USING (true) WITH CHECK (true);



ALTER TABLE "public"."bookings" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."cabins" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "delete all" ON "public"."bookings" FOR DELETE USING (true);



ALTER TABLE "public"."guests" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "insert all" ON "public"."bookings" FOR INSERT WITH CHECK (true);



ALTER TABLE "public"."menu" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."orders" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."ordersPizza" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."settings" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "update all" ON "public"."bookings" FOR UPDATE USING (true) WITH CHECK (true);



ALTER TABLE "public"."worldwise" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";

























































































































































GRANT ALL ON FUNCTION "public"."generate_short_id"() TO "anon";
GRANT ALL ON FUNCTION "public"."generate_short_id"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."generate_short_id"() TO "service_role";



GRANT ALL ON FUNCTION "public"."generate_short_id"("input_uuid" "uuid", "length" integer) TO "anon";
GRANT ALL ON FUNCTION "public"."generate_short_id"("input_uuid" "uuid", "length" integer) TO "authenticated";
GRANT ALL ON FUNCTION "public"."generate_short_id"("input_uuid" "uuid", "length" integer) TO "service_role";



GRANT ALL ON FUNCTION "public"."hash_decode"("text", "text", integer) TO "postgres";
GRANT ALL ON FUNCTION "public"."hash_decode"("text", "text", integer) TO "anon";
GRANT ALL ON FUNCTION "public"."hash_decode"("text", "text", integer) TO "authenticated";
GRANT ALL ON FUNCTION "public"."hash_decode"("text", "text", integer) TO "service_role";



GRANT ALL ON FUNCTION "public"."hash_encode"(bigint) TO "postgres";
GRANT ALL ON FUNCTION "public"."hash_encode"(bigint) TO "anon";
GRANT ALL ON FUNCTION "public"."hash_encode"(bigint) TO "authenticated";
GRANT ALL ON FUNCTION "public"."hash_encode"(bigint) TO "service_role";



GRANT ALL ON FUNCTION "public"."hash_encode"(bigint, "text") TO "postgres";
GRANT ALL ON FUNCTION "public"."hash_encode"(bigint, "text") TO "anon";
GRANT ALL ON FUNCTION "public"."hash_encode"(bigint, "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."hash_encode"(bigint, "text") TO "service_role";



GRANT ALL ON FUNCTION "public"."hash_encode"(bigint, "text", integer) TO "postgres";
GRANT ALL ON FUNCTION "public"."hash_encode"(bigint, "text", integer) TO "anon";
GRANT ALL ON FUNCTION "public"."hash_encode"(bigint, "text", integer) TO "authenticated";
GRANT ALL ON FUNCTION "public"."hash_encode"(bigint, "text", integer) TO "service_role";



GRANT ALL ON FUNCTION "public"."id_decode"("text") TO "postgres";
GRANT ALL ON FUNCTION "public"."id_decode"("text") TO "anon";
GRANT ALL ON FUNCTION "public"."id_decode"("text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."id_decode"("text") TO "service_role";



GRANT ALL ON FUNCTION "public"."id_decode"("text", "text") TO "postgres";
GRANT ALL ON FUNCTION "public"."id_decode"("text", "text") TO "anon";
GRANT ALL ON FUNCTION "public"."id_decode"("text", "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."id_decode"("text", "text") TO "service_role";



GRANT ALL ON FUNCTION "public"."id_decode"("text", "text", integer) TO "postgres";
GRANT ALL ON FUNCTION "public"."id_decode"("text", "text", integer) TO "anon";
GRANT ALL ON FUNCTION "public"."id_decode"("text", "text", integer) TO "authenticated";
GRANT ALL ON FUNCTION "public"."id_decode"("text", "text", integer) TO "service_role";



GRANT ALL ON FUNCTION "public"."id_decode"("text", "text", integer, "text") TO "postgres";
GRANT ALL ON FUNCTION "public"."id_decode"("text", "text", integer, "text") TO "anon";
GRANT ALL ON FUNCTION "public"."id_decode"("text", "text", integer, "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."id_decode"("text", "text", integer, "text") TO "service_role";



GRANT ALL ON FUNCTION "public"."id_decode_once"("text") TO "postgres";
GRANT ALL ON FUNCTION "public"."id_decode_once"("text") TO "anon";
GRANT ALL ON FUNCTION "public"."id_decode_once"("text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."id_decode_once"("text") TO "service_role";



GRANT ALL ON FUNCTION "public"."id_decode_once"("text", "text") TO "postgres";
GRANT ALL ON FUNCTION "public"."id_decode_once"("text", "text") TO "anon";
GRANT ALL ON FUNCTION "public"."id_decode_once"("text", "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."id_decode_once"("text", "text") TO "service_role";



GRANT ALL ON FUNCTION "public"."id_decode_once"("text", "text", integer) TO "postgres";
GRANT ALL ON FUNCTION "public"."id_decode_once"("text", "text", integer) TO "anon";
GRANT ALL ON FUNCTION "public"."id_decode_once"("text", "text", integer) TO "authenticated";
GRANT ALL ON FUNCTION "public"."id_decode_once"("text", "text", integer) TO "service_role";



GRANT ALL ON FUNCTION "public"."id_decode_once"("text", "text", integer, "text") TO "postgres";
GRANT ALL ON FUNCTION "public"."id_decode_once"("text", "text", integer, "text") TO "anon";
GRANT ALL ON FUNCTION "public"."id_decode_once"("text", "text", integer, "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."id_decode_once"("text", "text", integer, "text") TO "service_role";



GRANT ALL ON FUNCTION "public"."id_encode"(bigint[]) TO "postgres";
GRANT ALL ON FUNCTION "public"."id_encode"(bigint[]) TO "anon";
GRANT ALL ON FUNCTION "public"."id_encode"(bigint[]) TO "authenticated";
GRANT ALL ON FUNCTION "public"."id_encode"(bigint[]) TO "service_role";



GRANT ALL ON FUNCTION "public"."id_encode"(bigint) TO "postgres";
GRANT ALL ON FUNCTION "public"."id_encode"(bigint) TO "anon";
GRANT ALL ON FUNCTION "public"."id_encode"(bigint) TO "authenticated";
GRANT ALL ON FUNCTION "public"."id_encode"(bigint) TO "service_role";



GRANT ALL ON FUNCTION "public"."id_encode"(bigint[], "text") TO "postgres";
GRANT ALL ON FUNCTION "public"."id_encode"(bigint[], "text") TO "anon";
GRANT ALL ON FUNCTION "public"."id_encode"(bigint[], "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."id_encode"(bigint[], "text") TO "service_role";



GRANT ALL ON FUNCTION "public"."id_encode"(bigint, "text") TO "postgres";
GRANT ALL ON FUNCTION "public"."id_encode"(bigint, "text") TO "anon";
GRANT ALL ON FUNCTION "public"."id_encode"(bigint, "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."id_encode"(bigint, "text") TO "service_role";



GRANT ALL ON FUNCTION "public"."id_encode"(bigint[], "text", integer) TO "postgres";
GRANT ALL ON FUNCTION "public"."id_encode"(bigint[], "text", integer) TO "anon";
GRANT ALL ON FUNCTION "public"."id_encode"(bigint[], "text", integer) TO "authenticated";
GRANT ALL ON FUNCTION "public"."id_encode"(bigint[], "text", integer) TO "service_role";



GRANT ALL ON FUNCTION "public"."id_encode"(bigint, "text", integer) TO "postgres";
GRANT ALL ON FUNCTION "public"."id_encode"(bigint, "text", integer) TO "anon";
GRANT ALL ON FUNCTION "public"."id_encode"(bigint, "text", integer) TO "authenticated";
GRANT ALL ON FUNCTION "public"."id_encode"(bigint, "text", integer) TO "service_role";



GRANT ALL ON FUNCTION "public"."id_encode"(bigint[], "text", integer, "text") TO "postgres";
GRANT ALL ON FUNCTION "public"."id_encode"(bigint[], "text", integer, "text") TO "anon";
GRANT ALL ON FUNCTION "public"."id_encode"(bigint[], "text", integer, "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."id_encode"(bigint[], "text", integer, "text") TO "service_role";



GRANT ALL ON FUNCTION "public"."id_encode"(bigint, "text", integer, "text") TO "postgres";
GRANT ALL ON FUNCTION "public"."id_encode"(bigint, "text", integer, "text") TO "anon";
GRANT ALL ON FUNCTION "public"."id_encode"(bigint, "text", integer, "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."id_encode"(bigint, "text", integer, "text") TO "service_role";


















GRANT ALL ON TABLE "public"."bookings" TO "anon";
GRANT ALL ON TABLE "public"."bookings" TO "authenticated";
GRANT ALL ON TABLE "public"."bookings" TO "service_role";



GRANT ALL ON SEQUENCE "public"."bookings_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."bookings_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."bookings_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."cabins" TO "anon";
GRANT ALL ON TABLE "public"."cabins" TO "authenticated";
GRANT ALL ON TABLE "public"."cabins" TO "service_role";



GRANT ALL ON SEQUENCE "public"."cabins_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."cabins_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."cabins_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."guests" TO "anon";
GRANT ALL ON TABLE "public"."guests" TO "authenticated";
GRANT ALL ON TABLE "public"."guests" TO "service_role";



GRANT ALL ON SEQUENCE "public"."guests_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."guests_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."guests_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."menu" TO "anon";
GRANT ALL ON TABLE "public"."menu" TO "authenticated";
GRANT ALL ON TABLE "public"."menu" TO "service_role";



GRANT ALL ON TABLE "public"."orders" TO "anon";
GRANT ALL ON TABLE "public"."orders" TO "authenticated";
GRANT ALL ON TABLE "public"."orders" TO "service_role";



GRANT ALL ON TABLE "public"."ordersPizza" TO "anon";
GRANT ALL ON TABLE "public"."ordersPizza" TO "authenticated";
GRANT ALL ON TABLE "public"."ordersPizza" TO "service_role";



GRANT ALL ON SEQUENCE "public"."orders-pizza_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."orders-pizza_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."orders-pizza_id_seq" TO "service_role";



GRANT ALL ON SEQUENCE "public"."orders_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."orders_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."orders_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."settings" TO "anon";
GRANT ALL ON TABLE "public"."settings" TO "authenticated";
GRANT ALL ON TABLE "public"."settings" TO "service_role";



GRANT ALL ON SEQUENCE "public"."settings_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."settings_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."settings_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."worldwise" TO "anon";
GRANT ALL ON TABLE "public"."worldwise" TO "authenticated";
GRANT ALL ON TABLE "public"."worldwise" TO "service_role";



GRANT ALL ON SEQUENCE "public"."worldwise_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."worldwise_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."worldwise_id_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































